sudo: required

language: generic

services:
  - docker # travis will install docker

before_install:
- docker build -t kerys/docker-react-dev -f Dockerfile.dev .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-845030278225"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

